FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock README.md ./

RUN uv venv /app/.venv
RUN uv sync --no-cache

COPY src/ /app/src/

ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH=/app

CMD ["celery", "-A", "src.infrastructure.celery_app", "worker", "--loglevel=info"]